  <para>This software is copyrighted by Peter Simons
<email>simons@cryp.to</email>. Permission is granted to use it under the terms
of the GNU General Public License. For further details, refer to <ulink
url="http://www.gnu.org/licenses/gpl.html">http://www.gnu.org/licenses/gpl.html</ulink>.</para>

<!--
Local Variables:
mode: sgml
fill-column:80
sgml-parent-document:("mapson.sgml" "article" "appendix")
End:
-->
