.TH MAPSON 1
.SH NAME
mapson \- fiters unwanted junk mail
.SH SYNOPSIS
.B mapson
[
.B \-a
]
.SH DESCRIPTION
.PP
\fBmapSoN\fP is a really good spam filter.
.PP
Let's see what we have here.
.SH OPTIONS
.TP
.B \-a
Just an option to test nroff(1).
.SH FILES
.DT
.\"ta 0 12
$HOME/.mapsonrc     mapSoN config file.
.DT
.SH SEE ALSO
.PP
empty
.SH AUTHOR
.PP
Peter Simons <simons@rhein.de>
