  <cmdsynopsis>
    <command>mapson</command>
    <group>
      <arg choice="opt">-d</arg>
      <arg choice="opt">--debug</arg>
    </group>
    <group>
      <arg choice="opt">-c <replaceable>config</replaceable></arg>
      <arg choice="opt">--config-file <replaceable>config</replaceable></arg>
    </group>
    <arg choice="opt" rep="repeat"><replaceable>mail</replaceable></arg>
  </cmdsynopsis>

<!--
Local Variables:
mode: sgml
fill-column:80
sgml-parent-document:("mapson.sgml" "article" "sect1" "title" "blockquote")
End:
-->
